// Package proxy owns Traefik: it runs the Traefik container and writes its
// dynamic file-provider config. One YAML file per app, atomic writes.
// Containers get a stable network alias (app-<id8>) so config survives
// redeploys without rewriting.
package proxy

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	yaml "go.yaml.in/yaml/v3"

	"github.com/FyrmForge/stackr/internal/stackrd/config/envutil"
	"github.com/FyrmForge/stackr/internal/stackrd/infra/cluster"
	"github.com/FyrmForge/stackr/internal/stackrd/infra/envnet"
	"github.com/FyrmForge/stackr/internal/stackrd/infra/netpool"
	"github.com/FyrmForge/stackr/internal/stackrd/infra/runtime"
	"github.com/FyrmForge/stackr/internal/stackrd/store/repo"
)

const traefikImage = "traefik:v3.3"

type Proxy struct {
	// clus is every container and image call, on whichever node owns it; rt
	// is the same manager socket for the swarm half (services, overlays),
	// which is the manager's by definition.
	clus      *cluster.Cluster
	rt        *runtime.Runtime
	store     repo.Store
	dir       string // dataDir/traefik, mounted at /etc/traefik in the container
	httpPort  string
	httpsPort string
	acmeEmail string
	noTLS     bool
	// panelURL is where Traefik reaches stackr from inside the docker network,
	// the backend of the panel's own route. Not the public BASE_URL: that may
	// not resolve, or may route back through Traefik.
	panelURL string

	// panelHost is BASE_URL's hostname, the panel's own public name. The
	// panel is the one service that cannot be given a domain through the
	// panel, so its route is generated here rather than configured.
	panelHost string

	// probeURL / probeInterval / restart drive the route check in probe.go.
	// Fields rather than constants so the tests can point the probe at an
	// httptest server and count restarts without docker. Empty probeURL
	// disables the check.
	probeURL      string
	probeInterval time.Duration
	restart       func() error
}

func New(clus *cluster.Cluster, store repo.Store, dataDir, httpPort, httpsPort, acmeEmail, panelURL, panelHost string, noTLS bool) *Proxy {
	p := &Proxy{
		clus:      clus,
		rt:        clus.Runtime(),
		store:     store,
		dir:       filepath.Join(dataDir, "traefik"),
		httpPort:  httpPort,
		httpsPort: httpsPort,
		panelURL:  panelURL,
		panelHost: panelHost,
		acmeEmail: acmeEmail,
		noTLS:     noTLS,
		// The service name resolves to traefik's VIP on the shared stackr
		// network, which the panel and Traefik are both on.
		probeURL:      "http://" + runtime.TraefikService + "/",
		probeInterval: time.Second,
	}
	p.restart = p.restartTraefik
	return p
}

// dnsConfig returns the configured DNS-01 provider and its credential env
// lines ("" = wildcard certs disabled). Stored in global settings.
func (p *Proxy) dnsConfig(ctx context.Context) (provider string, env []string) {
	provider, _ = p.store.GetSetting(ctx, "dns_provider")
	raw, _ := p.store.GetSetting(ctx, "dns_env")
	return provider, envutil.Lines(raw)
}

// TileAlias is the tile's globally-unique DNS alias. Traefik sits on every
// environment network, so its target must be unique across envs (plain slugs
// are only unique within one env). Must match envnet.TileAlias.
func TileAlias(tileID string) string {
	return "tile-" + tileID[:8]
}

// tlsOff: no certificates at all, every route is served on the web entrypoint
// only. Meant for throwaway/LAN test hosts that no CA can reach. Custom-cert
// domains are ignored too; a test host has no use for them.
//
// Opt-in only (STACKR_TLS=off). Keying it on a missing ACME_EMAIL would strip
// HTTPS from every existing host that never set the variable, silently, on the
// next config write.
func (p *Proxy) tlsOff() bool { return p.noTLS }

// EnsureTraefik writes static config and starts the managed Traefik container
// if it is not already running.
func (p *Proxy) EnsureTraefik(ctx context.Context) error {
	dyn := filepath.Join(p.dir, "dynamic")
	if err := os.MkdirAll(dyn, 0o755); err != nil {
		return err
	}

	dnsProvider, dnsEnv := p.dnsConfig(ctx)
	trusted := p.trustedIPsLine(ctx)
	static := `# generated by stackr, do not edit
entryPoints:
  web:
    address: ":80"
` + trusted + `  websecure:
    address: ":443"
` + trusted + `providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true
`
	if !p.tlsOff() {
		static += `certificatesResolvers:
`
		// One resolver per distinct account. A single instance-wide address
		// meant every tenant's expiry notices went to the operator, and a
		// customer bringing their own domain could not bring their own
		// account. "le" stays the default so nothing that has one already
		// re-issues.
		for _, e := range p.acmeAccounts(ctx) {
			static += fmt.Sprintf(`  %s:
    acme:
      email: %q
      storage: /etc/traefik/%s.json
      httpChallenge:
        entryPoint: web
`, e.resolver, e.email, e.resolver)
		}
	}
	if dnsProvider != "" && !p.tlsOff() {
		// Credentials go in as container env; the hash comment makes credential
		// edits count as a static-config change so the container is recreated.
		envSum := sha256.Sum256([]byte(strings.Join(dnsEnv, "\n")))
		static += fmt.Sprintf(`  ledns:
    acme:
      email: %q
      storage: /etc/traefik/acme-dns.json
      dnsChallenge:
        provider: %s
# dnsEnv %x
`, p.acmeEmail, dnsProvider, envSum[:8])
	}
	static += `api:
  dashboard: false
log:
  level: INFO
accessLog:
  filePath: /etc/traefik/access.log
  format: json
`
	// Operator override (dokploy-style): a saved override replaces the whole
	// generated file verbatim, replace-not-merge, same semantics as the
	// per-tile traefik_override. Placed before the change compare so an
	// override edit recreates the container like any other static change.
	if ov, err := p.store.GetSetting(ctx, "traefik_static_override"); err == nil && strings.TrimSpace(ov) != "" {
		static = ov
	}
	staticPath := filepath.Join(p.dir, "traefik.yml")
	old, _ := os.ReadFile(staticPath)
	staticChanged := string(old) != static
	if err := atomicWrite(staticPath, static); err != nil {
		return err
	}
	// Global middlewares, regenerated every start so they survive pruning.
	if err := atomicWrite(filepath.Join(dyn, "_middlewares.yml"), `http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
`); err != nil {
		return err
	}

	if err := p.writePanel(); err != nil {
		return err
	}

	// A box that ran traefik as a plain container before the swarm move still
	// holds the name and ports 80/443; the service cannot bind until it is
	// gone. acme.json is on the host disk, so nothing is lost.
	if existing, err := p.clus.ListByLabel(ctx, "stackr.traefik", "true"); err == nil {
		for _, c := range existing {
			if c.TaskID == "" {
				_ = p.clus.StopRemove(ctx, p.clus.Self(ctx), c.ID)
			}
		}
	}

	if err := p.clus.PullImage(ctx, traefikImage, os.Stderr); err != nil {
		return fmt.Errorf("pull traefik: %w", err)
	}
	absDir, err := filepath.Abs(p.dir)
	if err != nil {
		return err
	}
	// Every pool overlay is in the spec at create. A service cannot join a
	// network without rolling every task, so traefik takes all of them up
	// front and an environment coming or going never touches it
	// (docs/plans/30-docker-swarm.md, decision 2).
	pool, err := p.rt.ListNetworks(ctx, netpool.EnvPrefix)
	if err != nil {
		return err
	}
	nets := []runtime.NetAttach{{Name: runtime.NetworkName}}
	for _, n := range pool {
		nets = append(nets, runtime.NetAttach{Name: n})
	}
	ports := map[string]string{p.httpPort: "80"}
	// With TLS off nothing listens behind 443, and publishing it anyway lets
	// a busy 443 on the box stop traefik from starting at all.
	if !p.noTLS {
		ports[p.httpsPort] = "443"
	}
	created, err := p.rt.EnsureService(ctx, runtime.ServiceSpec{
		Name:     runtime.TraefikService,
		Image:    traefikImage,
		Env:      dnsEnv,
		Labels:   map[string]string{"stackr.traefik": "true"},
		Mounts:   []string{absDir + ":/etc/traefik"},
		Networks: nets,
		Ports:    ports,
		// The routing mesh SNATs, which would hand every backend traefik's
		// address instead of the visitor's.
		HostPorts: true,
		// Pinned for acme.json: it lives on the manager's disk, and
		// start-first would run two traefiks against that one file for a few
		// seconds. Two writers on it corrupt it, so the roll is stop-first
		// and pays a short gap on 80 and 443.
		Pinned:      true,
		ManagerOnly: true,
	})
	if err != nil {
		return err
	}
	// Static config only loads at start, so a changed traefik.yml needs the
	// task rolled, the spec itself did not change, and swarm would leave the
	// running task alone. Never after a create: the task swarm is starting
	// right now already has the new file, and rolling it here only races
	// swarm's own version bump.
	if staticChanged && !created {
		if err := p.rt.RestartService(ctx, runtime.TraefikService, 1); err != nil {
			return err
		}
	}
	if err := p.reattach(ctx); err != nil {
		return err
	}
	go p.verify(p.panelHost)
	return nil
}

// reattach puts Traefik on any pool network its spec does not already carry,
// what pool growth produces, and re-records the addresses afterwards.
//
// All of them, claimed or not: joining a network later is exactly what a
// service cannot do cheaply, so the cost is paid once here rather than on
// every environment create. Nothing to add is the normal case and costs one
// inspect.
func (p *Proxy) reattach(ctx context.Context) error {
	nets, err := p.rt.ListNetworks(ctx, netpool.EnvPrefix)
	if err != nil {
		return err
	}
	attach := make([]runtime.NetAttach, 0, len(nets))
	for _, n := range nets {
		attach = append(attach, runtime.NetAttach{Name: n})
	}
	since := time.Now()
	rolled, err := p.rt.AttachServiceNetworks(ctx, runtime.TraefikService, attach)
	if err != nil {
		return err
	}
	if rolled {
		// The addresses below come off the running task's container. Reading
		// them mid-roll records the dying task's, and every
		// ${{ stackr.PROXY_IP }} goes stale with nothing to say why. Which is
		// why the wait is baselined: without it swarm's stale "completed"
		// answers yes before the roll has begun.
		if err := p.rt.WaitRolled(ctx, runtime.TraefikService, since, 90*time.Second); err != nil {
			return err
		}
	}
	p.recordAddrs(ctx, nets)
	return nil
}

// recordAddrs refreshes ${{ stackr.PROXY_IP }} / ${{ stackr.PROXY_CIDR }} for
// every environment Traefik just rejoined. A recreated Traefik gets new
// addresses from docker, so the values stored against each env are stale until
// this runs.
//
// The other half of the job is in envnet.Ensure, which covers an environment
// whose network did not exist when this swept, a new env, or a PR preview.
func (p *Proxy) recordAddrs(ctx context.Context, nets []string) {
	// A pooled network name says nothing about who holds it (infra/netpool);
	// environments.network is the only mapping, so read it off the rows.
	byNet := map[string]string{}
	stacks, err := p.store.ListStacks(ctx)
	if err != nil {
		return
	}
	for i := range stacks {
		envs, err := p.store.ListEnvironmentsByStack(ctx, stacks[i].ID)
		if err != nil {
			continue
		}
		if home, err := p.store.HomeEnvironment(ctx, stacks[i].ID); err == nil && home != nil {
			envs = append(envs, *home)
		}
		for _, e := range envs {
			if e.Network != "" {
				byNet[e.Network] = e.ID
			}
		}
	}
	for _, n := range nets {
		if envID, ok := byNet[n]; ok {
			envnet.RecordProxyAddr(ctx, p.store, p.clus, envID, n)
		}
	}
}

// WriteApp writes the dynamic config for an app's domains (or removes it when
// no domains exist). A non-empty TraefikOverride replaces the generated
// config verbatim, the DB stays the source of truth, this is just the render.
func (p *Proxy) WriteApp(app *repo.Tile, domains []repo.Domain) error {
	ctx := context.Background()
	// Nil in unit tests, which build a Proxy without a store: a missing list
	// simply means no resource names its own account, and every host lands on
	// the instance's resolver.
	var resources []repo.DomainResource
	if p.store != nil {
		resources, _ = p.store.ListDomainResources(ctx)
	}
	path := filepath.Join(p.dir, "dynamic", "app-"+app.ID+".yml")
	if app.TraefikOverride != "" {
		return atomicWrite(path, app.TraefikOverride)
	}
	if len(domains) == 0 {
		err := os.Remove(path)
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	id8 := app.ID[:8]

	// Per-app middlewares (basic auth, security-header preset). Basic auth is
	// first, so a request that is about to get a 401 skips the rest, and it
	// covers every router of the tile, hand-attached domains included.
	var mws []string
	var mwDefs strings.Builder
	entry, err := p.basicAuthEntry(ctx, app)
	if err != nil {
		// Leave whatever is on disk alone: rewriting it without the auth
		// middleware would publish the URL until the next successful sync.
		return err
	}
	if entry != "" {
		mws = append(mws, "app-"+id8+"-auth")
		fmt.Fprintf(&mwDefs, "    app-%s-auth:\n      basicAuth:\n        users:\n          - %s\n",
			id8, quoteYAML(entry))
	}
	if app.SecHeaders {
		mws = append(mws, "app-"+id8+"-hdr")
		fmt.Fprintf(&mwDefs, "    app-%s-hdr:\n      headers:\n        stsSeconds: 31536000\n        stsIncludeSubdomains: true\n        contentTypeNosniff: true\n        frameDeny: true\n", id8)
	}

	var b strings.Builder
	b.WriteString("# generated by stackr, do not edit\nhttp:\n  routers:\n")
	var certs []repo.Domain
	for i, d := range domains {
		name := fmt.Sprintf("app-%s-%d", id8, i)
		// A declared rule replaces the matcher only; the host still picks the
		// certificate below.
		rule := hostRule(d)
		if d.Rule != "" {
			rule = quoteYAML(d.Rule)
		}
		svc := name

		routerMws := append([]string(nil), mws...)
		// The operator's own after stackr's.
		for _, ref := range d.MiddlewareList() {
			routerMws = append(routerMws, p.stackMiddleware(ctx, app, ref))
		}
		prio := ""
		if d.Priority != 0 {
			prio = fmt.Sprintf("      priority: %d\n", d.Priority)
		}
		if d.RedirectTo != "" {
			// Redirect domains bypass auth/headers: the 301 fires first anyway.
			routerMws = []string{name + "-rd"}
			// target always gets https, a redirect target on plain
			// http is rare enough to hand-edit via override.
			fmt.Fprintf(&mwDefs, "    %s-rd:\n      redirectRegex:\n        regex: %s\n        replacement: %s\n        permanent: true\n",
				name, quoteYAML("^https?://"+regexpEscape(d.Host)+"/(.*)"), quoteYAML("https://"+d.RedirectTo+"/${1}"))
		}

		tls := "      tls:\n        certResolver: " + p.resolverFor(ctx, resources, d.Host) + "\n"
		switch {
		case d.CertPEM != "" && !p.tlsOff():
			certs = append(certs, d)
			tls = "      tls: {}\n" // Traefik picks the matching custom cert by SNI
		case strings.HasPrefix(d.Host, "*."):
			base := strings.TrimPrefix(d.Host, "*.")
			tls = fmt.Sprintf("      tls:\n        certResolver: ledns\n        domains:\n          - main: %q\n            sans: [%q]\n", base, d.Host)
		}

		if d.HTTPS && !p.tlsOff() {
			// Serving TLS and bouncing plain HTTP onto it are two questions.
			// force_https off leaves the http router serving the tile, so a
			// client that cannot follow a redirect still gets an answer.
			if d.ForceHTTPS {
				fmt.Fprintf(&b, "    %s-http:\n      rule: %s\n%s      entryPoints: [web]\n      middlewares: [https-redirect]\n      service: %s\n", name, rule, prio, svc)
			} else {
				fmt.Fprintf(&b, "    %s-http:\n      rule: %s\n%s      entryPoints: [web]\n%s      service: %s\n", name, rule, prio, middlewareLine(routerMws), svc)
			}
			fmt.Fprintf(&b, "    %s:\n      rule: %s\n%s      entryPoints: [websecure]\n%s%s      service: %s\n", name, rule, prio, middlewareLine(routerMws), tls, svc)
		} else {
			fmt.Fprintf(&b, "    %s:\n      rule: %s\n%s      entryPoints: [web]\n%s      service: %s\n", name, rule, prio, middlewareLine(routerMws), svc)
		}
	}
	if mwDefs.Len() > 0 {
		b.WriteString("  middlewares:\n")
		b.WriteString(mwDefs.String())
	}
	b.WriteString("  services:\n")
	for i, d := range domains {
		svc := fmt.Sprintf("app-%s-%d", id8, i)
		fmt.Fprintf(&b, "    %s:\n      loadBalancer:\n        servers:\n          - url: \"http://%s:%d\"\n", svc, TileAlias(app.ID), d.ContainerPort)
	}

	// Custom certs: PEMs land next to the config, referenced by a dynamic
	// tls.certificates block. Traefik matches them to requests by SNI.
	if len(certs) > 0 {
		certDir := filepath.Join(p.dir, "certs")
		if err := os.MkdirAll(certDir, 0o700); err != nil {
			return err
		}
		b.WriteString("tls:\n  certificates:\n")
		for _, d := range certs {
			if err := os.WriteFile(filepath.Join(certDir, d.ID+".crt"), []byte(d.CertPEM), 0o600); err != nil {
				return err
			}
			if err := os.WriteFile(filepath.Join(certDir, d.ID+".key"), []byte(d.KeyPEM), 0o600); err != nil {
				return err
			}
			fmt.Fprintf(&b, "    - certFile: /etc/traefik/certs/%s.crt\n      keyFile: /etc/traefik/certs/%s.key\n", d.ID, d.ID)
		}
	}
	if err := atomicWrite(path, b.String()); err != nil {
		return err
	}
	// Check Traefik actually picked the file up (probe.go). One host is
	// enough: the file loads or it does not. In a goroutine because this is
	// called from the apply loop and from settings handlers, and neither
	// should block on ten seconds of probing. Override files are skipped,
	// their hostnames are not ours to parse.
	go p.verify(domains[0].Host)
	return nil
}

// StackMiddlewareName is the traefik name of one entry in a stack's
// proxy.middlewares. Keyed on the stack id, not its slug: slugs repeat across
// orgs and change on rename, and either would silently point a router at
// someone else's middleware or at nothing.
func StackMiddlewareName(stackID, name string) string {
	return "stk-" + stackID[:8] + "-" + name
}

// stackMiddleware resolves a domain's middleware reference: a bare name is
// the tile's own stack's, stack/name another stack's in the same org. When
// the other stack is gone (renamed or deleted after the plan checked it) the
// name still goes on the router: traefik disables a router naming a
// middleware it cannot find, and a dead route beats a forwardAuth guard
// silently dropping off a public one.
func (p *Proxy) stackMiddleware(ctx context.Context, app *repo.Tile, ref string) string {
	stackSlug, name, cross := strings.Cut(ref, "/")
	if !cross {
		return StackMiddlewareName(app.StackID, ref) + "@file"
	}
	missing := "missing-" + stackSlug + "-" + name + "@file"
	if p.store == nil {
		return missing
	}
	own, err := p.store.GetStack(ctx, app.StackID)
	if err != nil || own == nil {
		return missing
	}
	other, err := p.store.GetStackBySlug(ctx, own.OrgID, stackSlug)
	if err != nil || other == nil {
		return missing
	}
	return StackMiddlewareName(other.ID, name) + "@file"
}

// WriteStackMiddlewares writes a stack's proxy.middlewares as
// dynamic/stack-<id>.yml, or removes the file when it has none. The bodies are
// the operator's raw traefik config; only the names are rewritten.
func (p *Proxy) WriteStackMiddlewares(s *repo.Stack) error {
	path := filepath.Join(p.dir, "dynamic", "stack-"+s.ID+".yml")
	var bodies map[string]any
	if s.ProxyMiddlewares != "" {
		if err := yaml.Unmarshal([]byte(s.ProxyMiddlewares), &bodies); err != nil {
			return fmt.Errorf("stack %s middlewares: %w", s.Slug, err)
		}
	}
	if len(bodies) == 0 {
		err := os.Remove(path)
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	named := make(map[string]any, len(bodies))
	for n, body := range bodies {
		named[StackMiddlewareName(s.ID, n)] = body
	}
	out, err := yaml.Marshal(map[string]any{"http": map[string]any{"middlewares": named}})
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return atomicWrite(path, "# generated by stackr, do not edit\n"+string(out))
}

// hostRule builds the router rule; wildcard hosts need HostRegexp.
func hostRule(d repo.Domain) string {
	var rule string
	if base, ok := strings.CutPrefix(d.Host, "*."); ok {
		rule = fmt.Sprintf("HostRegexp(`^[^.]+\\.%s$`)", regexpEscape(base))
	} else {
		rule = fmt.Sprintf("Host(`%s`)", d.Host)
	}
	if d.Path != "" && d.Path != "/" {
		rule += fmt.Sprintf(" && PathPrefix(`%s`)", d.Path)
	}
	return quoteYAML(rule)
}

func middlewareLine(mws []string) string {
	if len(mws) == 0 {
		return ""
	}
	return "      middlewares: [" + strings.Join(mws, ", ") + "]\n"
}

func regexpEscape(s string) string {
	return strings.ReplaceAll(s, ".", `\.`)
}

// Resync regenerates every app's dynamic config from the DB, heals a wiped
// or restored data dir at boot.
func (p *Proxy) Resync(ctx context.Context) error {
	tiles, err := p.store.ListTiles(ctx)
	if err != nil {
		return err
	}
	var failed []string
	for i := range tiles {
		t := &tiles[i]
		domains, err := p.store.ListDomainsByTile(ctx, t.ID)
		if err != nil {
			return err
		}
		if len(domains) == 0 && t.TraefikOverride == "" {
			continue // don't touch tiles with nothing to render
		}
		if err := p.WriteApp(t, domains); err != nil {
			// One tile whose settings cannot be read must not stop the rest
			// from syncing, at boot least of all. Its own route file is left
			// as it was, which is the protected version.
			log.Printf("proxy: resync %s: %v", t.Slug, err)
			failed = append(failed, t.Slug)
			continue
		}
	}
	// WriteApp already fired a verify per tile, but at boot they would all
	// race the same restart. Nothing else to do here: restartMu funnels them
	// into one restart and the rest confirm the route afterwards.
	// Operator-declared dynamic entries are DB state too, regenerate them so
	// a wiped/restored data dir heals like everything else.
	if err := p.SyncCustomDynamic(p.customEntries(ctx)); err != nil {
		return err
	}
	stacks, err := p.store.ListStacks(ctx)
	if err != nil {
		return err
	}
	for i := range stacks {
		if err := p.WriteStackMiddlewares(&stacks[i]); err != nil {
			return err
		}
	}
	if err := p.pruneOrphans("stack-", stackIDs(stacks)); err != nil {
		return err
	}
	if err := p.pruneOrphanApps(tiles); err != nil {
		return err
	}
	// The managed registry's route is DB state like everything else here, and
	// nothing but a domain save ever wrote it: a wiped data dir lost the route
	// until someone re-saved the domain. Whether the route exists must not
	// depend on which code path last ran.
	if reg, err := p.store.GetManagedRegistry(ctx); err == nil && reg != nil {
		if err := p.WriteRegistry(reg.Domain); err != nil {
			return err
		}
	}
	if len(failed) > 0 {
		return fmt.Errorf("could not rewrite routes for %s", strings.Join(failed, ", "))
	}
	return nil
}

// customEntries reads the operator's named dynamic entries (name -> raw yaml)
// from settings. Empty map when unset or unparsable.
func (p *Proxy) customEntries(ctx context.Context) map[string]string {
	raw, _ := p.store.GetSetting(ctx, "proxy_custom_dynamic")
	out := map[string]string{}
	if raw != "" {
		_ = json.Unmarshal([]byte(raw), &out)
	}
	return out
}

// SyncCustomDynamic materializes the named entries as dynamic/custom-<name>.yml
// and prunes custom-*.yml files no longer declared. Traefik's file provider
// watches the directory, so no restart is needed.
func (p *Proxy) SyncCustomDynamic(entries map[string]string) error {
	dir := filepath.Join(p.dir, "dynamic")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for name, body := range entries {
		if err := atomicWrite(filepath.Join(dir, "custom-"+name+".yml"), body); err != nil {
			return err
		}
	}
	des, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range des {
		n := e.Name()
		if e.IsDir() || !strings.HasPrefix(n, "custom-") || !strings.HasSuffix(n, ".yml") {
			continue
		}
		if _, ok := entries[strings.TrimSuffix(strings.TrimPrefix(n, "custom-"), ".yml")]; !ok {
			_ = os.Remove(filepath.Join(dir, n))
		}
	}
	return nil
}

// CurrentStatic is the traefik.yml actually on disk, the generated config,
// or the operator override when one is active.
func (p *Proxy) CurrentStatic() string {
	b, _ := os.ReadFile(filepath.Join(p.dir, "traefik.yml"))
	return string(b)
}

func stackIDs(stacks []repo.Stack) map[string]bool {
	out := make(map[string]bool, len(stacks))
	for i := range stacks {
		out[stacks[i].ID] = true
	}
	return out
}

// pruneOrphans deletes <prefix><id>.yml files whose id is not live, a deleted
// stack's middlewares.
func (p *Proxy) pruneOrphans(prefix string, live map[string]bool) error {
	dir := filepath.Join(p.dir, "dynamic")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, ".yml") {
			continue
		}
		if id := strings.TrimSuffix(strings.TrimPrefix(name, prefix), ".yml"); id == "" || live[id] {
			continue
		}
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

// pruneOrphanApps deletes app-<id>.yml files whose tile is gone. Resync only
// ever wrote files for tiles that still exist, so a tile deleted while the
// proxy was down (or a failed delete) left a live route to nothing.
// Deliberately narrow: only "app-<id>.yml" names are considered, so the
// hand-managed files in the same directory (_middlewares.yml, registry.yml) and
// anything else an operator dropped there are never touched.
func (p *Proxy) pruneOrphanApps(tiles []repo.Tile) error {
	dir := filepath.Join(p.dir, "dynamic")
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	live := make(map[string]bool, len(tiles))
	for i := range tiles {
		live[tiles[i].ID] = true
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasPrefix(name, "app-") || !strings.HasSuffix(name, ".yml") {
			continue
		}
		id := strings.TrimSuffix(strings.TrimPrefix(name, "app-"), ".yml")
		if id == "" || live[id] {
			continue
		}
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
			return err
		}
		log.Printf("proxy: removed stale route %s (tile no longer exists)", name)
	}
	return nil
}

// writePanel routes the panel's own hostname to the panel. It is generated,
// never configured: giving a tile a domain needs the panel, so a panel whose
// route lived in its own database could not be reached after a wipe, you
// would need the panel to get to the panel. Regenerated every boot, so a lost
// or emptied data dir heals itself.
//
// Skipped for a bare IP or localhost (a LAN box has no name to route and no
// certificate to get) and when BASE_URL is unset, which removes any file a
// previous boot wrote.
func (p *Proxy) writePanel() error {
	path := filepath.Join(p.dir, "dynamic", "panel.yml")
	if !p.routablePanel() {
		err := os.Remove(path)
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	rule := quoteYAML(fmt.Sprintf("Host(`%s`)", p.panelHost))
	routers := fmt.Sprintf(`    panel-http:
      rule: %s
      entryPoints: [web]
      middlewares: [https-redirect]
      service: panel
    panel:
      rule: %s
      entryPoints: [websecure]
      tls:
        certResolver: le
      service: panel
`, rule, rule)
	if p.tlsOff() {
		routers = fmt.Sprintf(`    panel:
      rule: %s
      entryPoints: [web]
      service: panel
`, rule)
	}
	return atomicWrite(path, `# generated by stackr, do not edit
http:
  routers:
`+routers+`  services:
    panel:
      loadBalancer:
        servers:
          - url: `+quoteYAML(strings.TrimRight(p.panelURL, "/"))+`
`)
}

// routablePanel reports whether the panel has a hostname worth a route.
func (p *Proxy) routablePanel() bool {
	if p.panelHost == "" || p.panelHost == "localhost" {
		return false
	}
	return net.ParseIP(p.panelHost) == nil
}

// WriteRegistry routes a TLS domain to the managed registry container (alias
// "registry" on the stackr network). Empty host removes the route.
func (p *Proxy) WriteRegistry(host string) error {
	path := filepath.Join(p.dir, "dynamic", "registry.yml")
	if host == "" {
		err := os.Remove(path)
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	rule := quoteYAML(fmt.Sprintf("Host(`%s`)", host))
	routers := fmt.Sprintf(`    registry-http:
      rule: %s
      entryPoints: [web]
      middlewares: [https-redirect]
      service: registry
    registry:
      rule: %s
      entryPoints: [websecure]
      tls:
        certResolver: le
      service: registry
`, rule, rule)
	if p.tlsOff() {
		routers = fmt.Sprintf(`    registry:
      rule: %s
      entryPoints: [web]
      service: registry
`, rule)
	}
	cfg := `# generated by stackr, do not edit
http:
  routers:
` + routers + `  services:
    registry:
      loadBalancer:
        servers:
          - url: "http://registry:5000"
`
	return atomicWrite(path, cfg)
}

// RemoveApp deletes an app's dynamic config file.
func (p *Proxy) RemoveApp(appID string) error {
	err := os.Remove(filepath.Join(p.dir, "dynamic", "app-"+appID+".yml"))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

func quoteYAML(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`) // regex escapes must survive YAML double-quoting
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

func atomicWrite(path, content string) error {
	// Unchanged content is not rewritten: every write here makes Traefik's
	// file provider reload, so a Resync only churns files that actually differ.
	if old, err := os.ReadFile(path); err == nil && string(old) == content {
		return nil
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// acmeAccount is one Let's Encrypt account the static config declares.
type acmeAccount struct {
	resolver string
	email    string
}

// acmeAccounts is the instance's account plus one per distinct address a
// domain resource names. The instance's is always "le", so a host that already
// has a certificate under it keeps using the same storage file.
func (p *Proxy) acmeAccounts(ctx context.Context) []acmeAccount {
	out := []acmeAccount{{resolver: "le", email: p.acmeEmail}}
	if p.store == nil {
		return out
	}
	seen := map[string]bool{strings.ToLower(p.acmeEmail): true}
	rs, err := p.store.ListDomainResources(ctx)
	if err != nil {
		return out
	}
	var extra []acmeAccount
	for _, r := range rs {
		e := strings.ToLower(strings.TrimSpace(r.ACMEEmail))
		if e == "" || seen[e] {
			continue
		}
		seen[e] = true
		extra = append(extra, acmeAccount{resolver: resolverName(e), email: e})
	}
	sort.Slice(extra, func(i, j int) bool { return extra[i].resolver < extra[j].resolver })
	return append(out, extra...)
}

// resolverName is a stable, YAML-safe name for one account. Derived from the
// address so the same address always maps to the same storage file, across
// restarts and across resources that share it.
func resolverName(email string) string {
	sum := sha256.Sum256([]byte(email))
	return "le-" + hex.EncodeToString(sum[:4])
}

// resolverFor picks the account a host's certificate is issued on: the
// longest-matching domain resource that names one, else the instance's.
//
// Longest match, because resources nest: an org owns example.com and a stack
// owns shop.example.com, and the stack's account is the nearer answer for a
// host under it.
func (p *Proxy) resolverFor(ctx context.Context, resources []repo.DomainResource, host string) string {
	_ = ctx
	best, bestLen := "le", -1
	h := strings.ToLower(strings.TrimPrefix(host, "*."))
	for _, r := range resources {
		e := strings.ToLower(strings.TrimSpace(r.ACMEEmail))
		if e == "" {
			continue
		}
		base := strings.ToLower(strings.TrimPrefix(r.Host, "*."))
		if h != base && !strings.HasSuffix(h, "."+base) {
			continue
		}
		if len(base) > bestLen {
			best, bestLen = resolverName(e), len(base)
		}
	}
	return best
}
