// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// SearchPalette is the global search overlay ("/" or the rail icon opens it,
// main.js drives it). Rendered once per page from Layout so it exists on
// canvases and settings pages alike; hidden until opened. Results come from
// GET /search as an HTML fragment.
func SearchPalette() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"search-palette\" class=\"hidden fixed inset-0 z-50\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Search\"><div class=\"absolute inset-0 scrim\" data-search-close></div><div class=\"relative mx-auto mt-[12vh] w-full max-w-xl panel bg-rw-surface border border-rw-border rounded-xl shadow-2xl overflow-hidden\"><input id=\"search-input\" type=\"text\" name=\"q\" placeholder=\"Search everything…\" autocomplete=\"off\" spellcheck=\"false\" class=\"w-full bg-transparent px-4 py-3 text-sm text-rw-text placeholder:text-rw-faint border-b border-rw-border focus:outline-none\" hx-get=\"/search\" hx-trigger=\"input changed delay:150ms\" hx-target=\"#search-results\" hx-swap=\"innerHTML\"><div id=\"search-results\" class=\"max-h-[50vh] overflow-y-auto\"><p class=\"px-4 py-6 text-sm text-rw-faint\">Search stacks, tiles, variables, settings…</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
