// Package managed owns managed instances (engine, admin credentials,
// endpoint, allow list, env pairs) and their provisions. The instance
// container is a plain tile (leaf/tile); engines and their commands live in
// flow/managed.
//
// step 7b task 5 replaces this: until then a consumer tile stands in as its
// own slice tile (provisions.tile_id = the consumer), so one consumer holds
// at most one slice, and the per-consumer outputs are not stored.
package managed

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"time"

	"github.com/google/uuid"

	"github.com/FyrmForge/stackr/internal/service/errs"
	"github.com/FyrmForge/stackr/internal/service/internal/address"
	"github.com/FyrmForge/stackr/internal/service/internal/slug"
	"github.com/FyrmForge/stackr/internal/service/internal/store"
)

const (
	Keep = "keep" // the consumer going away keeps the slice's data (default)
	Drop = "drop" // ... destroys it
)

type Leaf struct {
	instances  store.ManagedInstanceStore
	provisions store.ProvisionStore
}

func New(instances store.ManagedInstanceStore, provisions store.ProvisionStore) *Leaf {
	return &Leaf{instances: instances, provisions: provisions}
}

func secret() string {
	b := make([]byte, 24)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// Create makes the instance row for a managed tile, with a fresh admin
// password and no allow list (the tile's own env only). endpoint is where
// slices reach it (the flow knows the alias).
func (l *Leaf) Create(
	ctx context.Context,
	tileID, engine, adminUser, endpoint string,
) (store.ManagedInstance, error) {
	if engine == "" || adminUser == "" {
		return store.ManagedInstance{}, errs.Invalidf("engine", "an instance needs an engine and an admin user")
	}
	m := store.ManagedInstance{
		ID:            uuid.NewString(),
		TileID:        tileID,
		Engine:        engine,
		AdminUser:     adminUser,
		AdminPassword: secret(),
		Endpoint:      endpoint,
		CreatedAt:     time.Now().UTC(),
	}
	return m, l.instances.Create(ctx, m)
}

func (l *Leaf) Get(ctx context.Context, id string) (store.ManagedInstance, error) {
	return l.instances.Get(ctx, id)
}

func (l *Leaf) GetByTile(ctx context.Context, tileID string) (store.ManagedInstance, error) {
	return l.instances.GetByTile(ctx, tileID)
}

func (l *Leaf) SetEndpoint(
	ctx context.Context,
	m store.ManagedInstance,
	endpoint string,
) (store.ManagedInstance, error) {
	m.Endpoint = endpoint
	return m, l.instances.Update(ctx, m)
}

// SetAllow replaces the instance's allow list. Every entry is checked
// against the instance's own org first; a bad one leaves the row as it was.
// Nothing is torn down: a slice the list no longer admits fails at its next
// deploy (step 7b task 5).
func (l *Leaf) SetAllow(
	ctx context.Context,
	m store.ManagedInstance,
	orgSlug string,
	list []string,
) (store.ManagedInstance, error) {
	if _, err := address.ParseAllow(orgSlug, list); err != nil {
		return m, err
	}
	m.Allow = list
	return m, l.instances.Update(ctx, m)
}

// SetEnvPairs replaces the instance's consumer env name → own env name map.
func (l *Leaf) SetEnvPairs(
	ctx context.Context,
	m store.ManagedInstance,
	pairs map[string]string,
) (store.ManagedInstance, error) {
	for k, v := range pairs {
		if !slug.Valid(k) || !slug.Valid(v) {
			return m, errs.Invalidf("env_pairs", "%s: %s: both are environment names", k, v)
		}
	}
	m.EnvPairs = pairs
	return m, l.instances.Update(ctx, m)
}

// Teardown is step one of removing an instance: refused while slices are
// held unless force (the caller's, never a constant), else the distinct
// slices the flow must drop before the container goes. Several consumer
// rows can share one slice, so they are deduped by database name.
func (l *Leaf) Teardown(ctx context.Context, m store.ManagedInstance, force bool) ([]store.Provision, error) {
	held, err := l.provisions.ListByInstance(ctx, m.ID)
	if err != nil {
		return nil, err
	}
	if len(held) > 0 && !force {
		return nil, errs.Conflictf("%d consumer(s) hold slices on this instance; "+
			"detach them first, or force the delete to destroy the data with it", len(held))
	}
	seen := map[string]bool{}
	var drop []store.Provision
	for _, p := range held {
		if !seen[p.DBName] {
			seen[p.DBName] = true
			drop = append(drop, p)
		}
	}
	return drop, nil
}

// Delete removes the instance row; every provision still pointing at it
// goes with it (cascade), dropped by the engine or not, so none outlives it.
func (l *Leaf) Delete(ctx context.Context, id string) error { return l.instances.Delete(ctx, id) }

// Slice is a new provision as the flow built it (name uniquified against
// SliceNames, credentials generated by the engine or by Password).
type Slice struct {
	DBName, DBUser, DBPassword string
	Public                     bool
	OnRemove                   string // keep (default) | drop
}

// Password is a fresh slice password.
func Password() string { return secret() }

// SliceNames are the instance's taken slice names, for uniquifying.
func (l *Leaf) SliceNames(ctx context.Context, instanceID string) ([]string, error) {
	ps, err := l.provisions.ListByInstance(ctx, instanceID)
	names := make([]string, len(ps))
	for i, p := range ps {
		names[i] = p.DBName
	}
	return names, err
}

// Provision records a consumer's slice after the engine made it. One slice
// per consumer (the consumer stands in as the slice tile, see the package
// doc).
func (l *Leaf) Provision(
	ctx context.Context,
	m store.ManagedInstance,
	consumerTileID string,
	s Slice,
) (store.Provision, error) {
	if s.OnRemove == "" {
		s.OnRemove = Keep
	}
	if s.OnRemove != Keep && s.OnRemove != Drop {
		return store.Provision{}, errs.Invalidf("on_remove", "must be keep or drop")
	}
	if s.DBName == "" || s.DBUser == "" {
		return store.Provision{}, errs.Invalidf("slice", "a slice needs a name and a user")
	}
	if p, ok, err := l.find(ctx, consumerTileID); err != nil || ok {
		if ok {
			err = errs.Conflictf("this tile already has slice %s", p.DBName)
		}
		return store.Provision{}, err
	}
	p := store.Provision{
		ID:         uuid.NewString(),
		TileID:     consumerTileID,
		InstanceID: m.ID,
		DBName:     s.DBName,
		DBUser:     s.DBUser,
		DBPassword: s.DBPassword,
		Public:     s.Public,
		OnRemove:   s.OnRemove,
		CreatedAt:  time.Now().UTC(),
	}
	return p, l.provisions.Create(ctx, p)
}

// Share attaches a consumer to an existing slice. Same env only (fact):
// the slice's url secret is env-scoped.
func (l *Leaf) Share(
	ctx context.Context,
	of store.Provision,
	consumerTileID string,
	sameEnv bool,
) (store.Provision, error) {
	if !sameEnv {
		return store.Provision{}, errs.Refusedf("an existing slice can only be shared inside its environment")
	}
	if _, ok, err := l.find(ctx, consumerTileID); err != nil || ok {
		if ok {
			err = errs.Conflictf("this tile already has a slice")
		}
		return store.Provision{}, err
	}
	p := of
	p.ID, p.TileID, p.CreatedAt = uuid.NewString(), consumerTileID, time.Now().UTC()
	return p, l.provisions.Create(ctx, p)
}

func (l *Leaf) find(ctx context.Context, tileID string) (store.Provision, bool, error) {
	p, err := l.provisions.GetByTile(ctx, tileID)
	if errors.Is(err, errs.ErrNotFound) {
		return p, false, nil
	}
	return p, err == nil, err
}

func (l *Leaf) GetProvision(ctx context.Context, id string) (store.Provision, error) {
	return l.provisions.Get(ctx, id)
}

// ForConsumer is the consumer's slice, none or one (see the package doc).
func (l *Leaf) ForConsumer(ctx context.Context, tileID string) ([]store.Provision, error) {
	p, ok, err := l.find(ctx, tileID)
	if !ok {
		return nil, err
	}
	return []store.Provision{p}, nil
}

func (l *Leaf) ByInstance(ctx context.Context, instanceID string) ([]store.Provision, error) {
	return l.provisions.ListByInstance(ctx, instanceID)
}

// Outputs are a slice's published values. The provision no longer holds
// them; they are the consumer's binding's.
// step 7b task 5 replaces this: a ref to a slice output resolves to nothing
// until Bind mints the consumer's outputs.
func Outputs(store.Provision) map[string]string { return map[string]string{} }

// SetOutputs is a no-op until the binding holds the outputs.
// step 7b task 5 replaces this.
func (l *Leaf) SetOutputs(_ context.Context, p store.Provision, _ map[string]string) (store.Provision, error) {
	return p, nil
}

// SetPublic flips public read. A public slice needs the instance to have a
// public base URL (fact), or browsers could not reach it anyway.
func (l *Leaf) SetPublic(
	ctx context.Context,
	p store.Provision,
	public bool,
	publicBase string,
) (store.Provision, error) {
	if public && publicBase == "" {
		return p, errs.Refusedf("give the instance a public domain before making a slice public")
	}
	p.Public = public
	return p, l.provisions.Update(ctx, p)
}

// Release is a consumer letting go of its slice (removed from the file, or
// the tile going). on_remove drop or an ephemeral env (fact) says the flow
// must drop it and then call DropRow; keep leaves the row as it is.
// step 7b task 5 replaces this: there is no orphan state any more (the
// provision belongs to its slice tile); Unbind deletes the consumer's binding.
func (l *Leaf) Release(_ context.Context, p store.Provision, ephemeral bool) (drop bool, err error) {
	return p.OnRemove == Drop || ephemeral, nil
}

// DropRow removes a slice row after the engine dropped it.
func (l *Leaf) DropRow(ctx context.Context, id string) error { return l.provisions.Delete(ctx, id) }
